### ISSUE TITLE
Need help? Cleaned data not 100% tidy

### ISSUE THREAD

**Issue by rrmn** [jldbc/coffee-quality-database#1]
Hey @jldbc ,

thank you for your work. I tried to play around with it and noticed that there are some missing values that are encoded as empty strings, potential duplicates, unstructured data (e.g., the weights). Would you mind if I try to improve a bit on your data? 

Best,
Roman

**Comment by jldbc** [comment]
Feel free! There's a ton of cleaning and standardization work that this could benefit from.

**Comment by Kotick10** [comment]
Hey @jldbc ,

I am using this dataset as one of my resources for my economics capstone. I have cleaned the data, deleting the rolls that had blank spaces, researching and substituting the name of the micro-regions by the name of the countries, grouped the processing methods into 5 methods, and translated all altitude means into meters. Would you like to have this file? Let me know--it is a lot more useful for analysis.

**Comment by kinseymatthews** [comment]
Hey @Kotick10 

I was hoping to use this dataset for my stats class and would be interested in seeing the file that you cleaned up. Is there any way I could get access to it?

Thanks!

**Comment by Kotick10** [comment]
Hey @KinsMatt,

The file that I cleaned up was the original data from this website. All the values from here were taken from the coffee quality institute. 

I have edited the qualitative data for use in SPSS through inputing binary variables.

Let me know if you need something else.

[https://docs.google.com/spreadsheets/d/1rO00cO1GxdSb0veRKKcWjaNk-2GS-oLxexlV_y3Zxdo/edit?usp=sharing](url)
